### ISSUE TITLE
Binary/manifest needs updating to 5.9.84

### ISSUE THREAD

**Issue by develroo** [flathub/net.codeindustry.MasterPDFEditor#82]
Current version of the flatpak is 5.9.2. A newer version is available from [here](https://code-industry.net/public/master-pdf-editor-5.9.84.x86_64-qt5_include.tar.gz)

**Comment by muelli** [comment]
should be 5.9.82: https://github.com/flathub/net.codeindustry.MasterPDFEditor/pull/78

dunno why the bot is not picking the new version up. maybe you can investigate.

**Comment by develroo** [comment]
Hmmm it just updated to 5.9.82, which is consistent with the manifest now. 

```
 sources:
      - type: extra-data
        url: https://code-industry.net/public/master-pdf-editor-5.9.82-qt5.x86_64.tar.gz
        filename: master-pdf-editor.tar.gz
        sha256: 09bae18502748a25f3f21509122fbfc5bd9919bba7b8fb882209824602613555
        size: 80442378
        
```

But the new version is still 5.9.84?
